# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f123515271abdef863134fa8a87cf2b073de2b624374681a6d2443c4be3008fc2fa515e50635cb50771c573b04dd75c8ce0e0127e0ca954b6dfa6eefd12136d

test:
  secret_key_base: bb8925fcbdbda3db7b35b0f73ad038a4a4f83b86da5d9d9b4481d4686c33a89bba793f49877bca3db7c6da61df0f3464624e7c543562bef3df43b37467562816

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
